const User = require('../models/User');

// Generate token and send response
const sendTokenResponse = (user, statusCode, res, message) => {
    const token = user.getSignedJwtToken();

    const userResponse = {
        id: user._id,
        name: user.name,
        email: user.email,
        phone: user.phone,
        workplace: user.workplace,
        avatar: user.avatar,
        emergencyContacts: user.emergencyContacts,
        ridesOffered: user.ridesOffered,
        ridesTaken: user.ridesTaken,
        moneySaved: user.moneySaved,
        rating: user.rating,
        reviewCount: user.reviewCount,
        isVerified: user.isVerified,
        licenseVerified: user.licenseVerified,
        role: user.role
    };

    res.status(statusCode).json({
        success: true,
        message,
        token,
        user: userResponse
    });
};

// @desc    Register user
// @route   POST /api/auth/register
// @access  Public
exports.register = async (req, res) => {
    try {
        const { name, email, phone, password, workplace, emergencyContacts } = req.body;

        // Validate required fields
        if (!name || !email || !password) {
            return res.status(400).json({
                success: false,
                message: 'Please provide name, email and password'
            });
        }

        // Validate email format
        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        if (!emailRegex.test(email)) {
            return res.status(400).json({
                success: false,
                message: 'Please provide a valid email address'
            });
        }

        // Validate password strength
        if (password.length < 6) {
            return res.status(400).json({
                success: false,
                message: 'Password must be at least 6 characters long'
            });
        }

        // Check if user exists
        const existingUser = await User.findOne({ email });
        if (existingUser) {
            return res.status(409).json({ // 409 Conflict is more appropriate
                success: false,
                message: 'User already exists with this email'
            });
        }

        // Create user
        const user = await User.create({
            name: name.trim(),
            email: email.toLowerCase().trim(),
            phone: phone?.trim(),
            password,
            workplace: workplace?.trim(),
            emergencyContacts: emergencyContacts || []
            // avatar will be generated in pre-save middleware
        });

        // If avatar wasn't generated by pre-save, generate it
        if (!user.avatar && user.generateAvatar) {
            user.avatar = user.generateAvatar();
            await user.save();
        }

        sendTokenResponse(user, 201, res, 'User registered successfully');

    } catch (error) {
        console.error('Registration error:', error);

        // Handle specific mongoose errors
        if (error.name === 'ValidationError') {
            const messages = Object.values(error.errors).map(val => val.message);
            return res.status(400).json({
                success: false,
                message: 'Validation error',
                error: messages.join(', ')
            });
        }

        if (error.code === 11000) {
            return res.status(400).json({
                success: false,
                message: 'Duplicate field value entered'
            });
        }

        res.status(500).json({
            success: false,
            message: 'Error in registering user',
            error: process.env.NODE_ENV === 'production' ? 'Server error' : error.message
        });
    }
};

// @desc    Login user
// @route   POST /api/auth/login
// @access  Public
exports.login = async (req, res) => {
    try {
        const { email, password } = req.body;

        // Validate email & password
        if (!email || !password) {
            return res.status(400).json({
                success: false,
                message: 'Please provide email and password'
            });
        }

        // Check for user with password field
        const user = await User.findOne({ email: email.toLowerCase().trim() }).select('+password');

        if (!user) {
            return res.status(401).json({
                success: false,
                message: 'Invalid credentials'
            });
        }

        // Check if user account is active
        if (user.status && user.status !== 'active') {
            return res.status(401).json({
                success: false,
                message: 'Your account has been suspended. Please contact support.'
            });
        }

        // Check if password matches
        const isMatch = await user.matchPassword(password);

        if (!isMatch) {
            return res.status(401).json({
                success: false,
                message: 'Invalid credentials'
            });
        }

        sendTokenResponse(user, 200, res, 'Login successful');

    } catch (error) {
        console.error('Login error:', error);
        res.status(500).json({
            success: false,
            message: 'Error in login',
            error: process.env.NODE_ENV === 'production' ? 'Server error' : error.message
        });
    }
};

// @desc    Get current logged in user
// @route   GET /api/auth/me
// @access  Private
exports.getMe = async (req, res) => {
    try {
        const user = await User.findById(req.user.id);

        if (!user) {
            return res.status(404).json({
                success: false,
                message: 'User not found'
            });
        }

        res.status(200).json({
            success: true,
            user: {
                id: user._id,
                name: user.name,
                email: user.email,
                phone: user.phone,
                workplace: user.workplace,
                avatar: user.avatar,
                emergencyContacts: user.emergencyContacts,
                ridesOffered: user.ridesOffered,
                ridesTaken: user.ridesTaken,
                moneySaved: user.moneySaved,
                rating: user.rating,
                reviewCount: user.reviewCount,
                isVerified: user.isVerified,
                licenseVerified: user.licenseVerified,
                role: user.role,
                status: user.status,
                createdAt: user.createdAt
            }
        });
    } catch (error) {
        console.error('Get user error:', error);
        res.status(500).json({
            success: false,
            message: 'Error getting user data',
            error: process.env.NODE_ENV === 'production' ? 'Server error' : error.message
        });
    }
};

// @desc    Update user profile
// @route   PUT /api/auth/profile
// @access  Private
exports.updateProfile = async (req, res) => {
    try {
        const { name, email, phone, workplace, emergencyContacts } = req.body;

        // Build update object with only provided fields
        const updateFields = {};
        if (name) updateFields.name = name.trim();
        if (email) updateFields.email = email.toLowerCase().trim();
        if (phone) updateFields.phone = phone.trim();
        if (workplace) updateFields.workplace = workplace.trim();
        if (emergencyContacts) updateFields.emergencyContacts = emergencyContacts;

        // Check if email is being updated and if it already exists
        if (email && email !== req.user.email) {
            const existingUser = await User.findOne({ email: email.toLowerCase().trim() });
            if (existingUser && existingUser._id.toString() !== req.user.id) {
                return res.status(409).json({
                    success: false,
                    message: 'Email already exists'
                });
            }
        }

        const user = await User.findByIdAndUpdate(
            req.user.id, 
            updateFields, 
            {
                new: true,
                runValidators: true
            }
        );

        if (!user) {
            return res.status(404).json({
                success: false,
                message: 'User not found'
            });
        }

        res.status(200).json({
            success: true,
            message: 'Profile updated successfully',
            user: {
                id: user._id,
                name: user.name,
                email: user.email,
                phone: user.phone,
                workplace: user.workplace,
                avatar: user.avatar,
                emergencyContacts: user.emergencyContacts,
                ridesOffered: user.ridesOffered,
                ridesTaken: user.ridesTaken,
                moneySaved: user.moneySaved,
                rating: user.rating,
                reviewCount: user.reviewCount
            }
        });

    } catch (error) {
        console.error('Update profile error:', error);

        // Handle specific mongoose errors
        if (error.name === 'ValidationError') {
            const messages = Object.values(error.errors).map(val => val.message);
            return res.status(400).json({
                success: false,
                message: 'Validation error',
                error: messages.join(', ')
            });
        }

        if (error.code === 11000) {
            return res.status(400).json({
                success: false,
                message: 'Email already exists'
            });
        }

        res.status(500).json({
            success: false,
            message: 'Error updating profile',
            error: process.env.NODE_ENV === 'production' ? 'Server error' : error.message
        });
    }
};

// @desc    Change password
// @route   PUT /api/auth/change-password
// @access  Private
exports.changePassword = async (req, res) => {
    try {
        const { currentPassword, newPassword } = req.body;

        if (!currentPassword || !newPassword) {
            return res.status(400).json({
                success: false,
                message: 'Please provide current password and new password'
            });
        }

        if (newPassword.length < 6) {
            return res.status(400).json({
                success: false,
                message: 'New password must be at least 6 characters long'
            });
        }

        const user = await User.findById(req.user.id).select('+password');

        // Check current password
        const isMatch = await user.matchPassword(currentPassword);
        if (!isMatch) {
            return res.status(401).json({
                success: false,
                message: 'Current password is incorrect'
            });
        }

        // Update password
        user.password = newPassword;
        await user.save();

        res.status(200).json({
            success: true,
            message: 'Password updated successfully'
        });

    } catch (error) {
        console.error('Change password error:', error);
        res.status(500).json({
            success: false,
            message: 'Error changing password',
            error: process.env.NODE_ENV === 'production' ? 'Server error' : error.message
        });
    }
};

// @desc    Logout user (client-side token removal)
// @route   POST /api/auth/logout
// @access  Private
exports.logout = async (req, res) => {
    try {
        // In a stateless JWT system, logout is handled client-side by removing the token
        // For server-side logout, you could maintain a blacklist (more complex)
        
        res.status(200).json({
            success: true,
            message: 'Logged out successfully'
        });
    } catch (error) {
        console.error('Logout error:', error);
        res.status(500).json({
            success: false,
            message: 'Error during logout',
            error: process.env.NODE_ENV === 'production' ? 'Server error' : error.message
        });
    }
};